#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

### AUTOSTART ###

# Tray items
nm-applet &

# Notifications
dunst -conf ~/.config/dunst/dunstrc &

# Set default cursor
xsetroot -cursor_name left_ptr &

# Set mouse sensivity
xinput --set-prop 8 305 -0.30 &

# For stop tearing
picom -f &

# Polybar
$HOME/.config/polybar/launch.sh
	
# Set wallpaper
~/.scripts/.fehbg

# Set language switch
setxkbmap -model pc105 -option grp:win_space_toggle us,ru &

# Set hotkeys handle
pgrep -x sxhkd > /dev/null || sxhkd &

##  Settings ###
bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color $(xgetres foreground)
bspc config normal_border_color $(xgetres background)

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Org.gnome.Nautilus desktop='^4' state=floating follow=on
bspc rule -a XTerm:floating state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Code desktop='^3' follow=on
bspc rule -a TelegramDesktop state=floating desktop='^5' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# xprop | grep WM_CLASS for windowName

